### ISSUE TITLE
How to generate TERMSRV* codes from keyboard

### ISSUE THREAD

**Issue by aegonzalez** [oblitum/Interception#37]
A key is accompanied by an InterceptionKeyState. I understand the KEY_DOWN, KEY_UP and E0 and E1 states but what is TERMSRV_SET_LED, TERMSRV_SHADOW and TERMSRV_VKPACKET? How do you generate those states?
Thanks.

**Comment by oblitum** [comment]
I don't know since I didn't found internal driver documentation about those. When I've written Interception I cared about being able to exposed all low level functionality, and even though those flags were present, I have never tried to produced them myself.

From their prefix, my suspicion is that they are related to Terminal Services console session devices.

**Comment by oblitum** [comment]
Closing as this was more a doubt which I simply can't answer as these flags are provided by Windows but I dunno about their usage.
