### ISSUE TITLE
How to tell if Interception Driver is installed

### ISSUE THREAD

**Issue by aegonzalez** [oblitum/Interception#38]
Hi,
Is there a registry entry or other means besides using the devicetree tool to determine if the interception driver is installed?
thanks.

**Comment by oblitum** [comment]
Hi. The `DeviceTree` tool is one good tool to check drivers that are actually loaded by the system, another tool is the `driverquery` Windows command.

About the drivers, you may check the registry entries and/or driver files path, it can be checked from installer sources. If you wish me to point which parts of the sources or ask any driver/installer source related information, please use the private repository issue tracker instead of this one, since this one regards the library solely.
