### ISSUE TITLE
Inteceptor Driver blacklisted by anticheat 

### ISSUE THREAD

**Issue by ronald0231** [oblitum/Interception#44]
So this online game anti cheat developer decided your driver interceptor is not healthy for their community so they blacklisted it (the game won't run if interceptor is installed whether it is being detected through your driver signature. Driver name in mouse and keyboard or port I don't know :( ) is there a way to bypass fix it 
Thank you

**Comment by oblitum** [comment]
Hi. Sorry but I give no support in bypassing specific anticheat systems since there can be any amount of them and they can apply many individual unknown techniques to do so. If there's interest in patching library or drivers internally to achieve this objective, the only option available is obtaining sources through a commercial license.

**Comment by winifix** [comment]
@ronald0231 Which game's anti-cheat or which anti-cheat?

**Comment by Liiion911** [comment]
> @ronald0231 Which game's anti-cheat or which anti-cheat?

lineage 2 guards block this driver.
I think they know driverName...
