### ISSUE TITLE
Press “Pause Break” key , thread block

### ISSUE THREAD

**Issue by magicdmer** [oblitum/Interception#47]
I build the cadstop sample and run it in windows 7 x86, all is ok utill i press "Pause Break" key. 
I use procexp look up the thread , found the thread is blocked with State: Wait:WrLpcReply.

**Comment by oblitum** [comment]
Per twitter you said your problem was because you clicked Pause Break on the console Windows, which just paused the thread correct?

Notice that the caps2esc sample is a console program but if you build it using the build scripts provided in this repository, using the WDK, you get a program that doesn't create any console Windows and hence you shouldn't be able to pause it without a window.

Just for record, is that what happened? You're building it without the provided scripts and is getting a console window when executing it?

**Comment by oblitum** [comment]
Notice how [the build file for caps2esc](https://github.com/oblitum/Interception/blob/master/samples/caps2esc/sources#L3) differs from [others](https://github.com/oblitum/Interception/blob/master/samples/identify/sources#L3). As you can see caps2esc is set to be a Windows program, not a console one.

**Comment by oblitum** [comment]
All OK as you reported.
