### ISSUE TITLE
Mouse and keyboard not working. Problem with uninstalling without a command line.

### ISSUE THREAD

**Issue by iAmFunky** [oblitum/Interception#83]
I've followed Tutorial how to have 2nd keyboard attached as a way of having more hotkeys. Everything was working perfectly until 2nd keyboard stopped working. I typed command to uninstall it (install-interception.exe / ininstall. I tried deleting keyboard.sys file from sys32 and moving the mouse file to Desktop. Everything went back to normal but after a reboot, I forgot to place the mouse.sys file back into the sys32 dir. Now my Mouse and Keyboard doesnt work. Ive tried switching mouses and keyboards but that didnt work.

Is there a way to uninstall interception without a command line?

**Comment by oblitum** [comment]
> Is there a way to uninstall interception without a command line?

Sorry, but no, and even if there was, it would be a program which you need to execute somehow, using keyboard and mouse. The current installer has fixed a previous issue regarding uninstall, the drivers files are removed after reboot, because Windows is picky about driver remotion, you shouldn't have done it manually in the first place. If for whatever reason you have got an error message, you should have run /install and then /uninstall to uninstall it cleanly. The only thing to available to revert the registry changes would be a restore point or something in that sense.

**Comment by iAmFunky** [comment]
Ok, found a solution! I found my old graphic tablet and connected it to my pc. Thankfully it is NOT treated as a mouse (which doesnt work), so Ive managed to install VNC with my Pen and virtual windows keyboard. Then I installed it and uninstalled it, deleted keyboard and mouse drivers and everything went back to normal. What a day

**Comment by oblitum** [comment]
Great news!

**Comment by TheDarkBomber** [comment]
Wait, you're just expecting people to fix an issue that effectively renders their system on their own by either re-installing Windows or having a graphic tablet handy instead of actually fixing this outstanding issue?

**Comment by oblitum** [comment]
@TheDarkBomber Did you read my previous comment?

> The **current installer has fixed a previous issue regarding uninstall**, the drivers files are removed after reboot, because Windows is picky about driver remotion, **you shouldn't have done it manually in the first place**.

Many people and clients use it in their system without issues, including me. I have absolutely no idea what happens when people, specially non-programmers (given this lib/driver is made for that audience), install it from non-official sources for example or fiddle with driver deletion by themselves and what not, they won't have another option but fix their stuff themselves, there's nothing that this project can do about that.
